/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.entity.generator.sample;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ExampleObject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2885593688887424005L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ExampleObject\",\"namespace\":\"com.entity.generator.sample\",\"fields\":[{\"name\":\"field1\",\"type\":\"string\",\"doc\":\"Name of the user account on Thecodebuzz.com\"},{\"name\":\"field2\",\"type\":\"string\",\"doc\":\"The email of the user logging message on the blog\"},{\"name\":\"field3\",\"type\":\"long\",\"doc\":\"time in seconds\"}],\"doc:\":\"A basic schema for storing thecodebuzz blogs messages\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ExampleObject> ENCODER =
      new BinaryMessageEncoder<ExampleObject>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ExampleObject> DECODER =
      new BinaryMessageDecoder<ExampleObject>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ExampleObject> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ExampleObject> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ExampleObject> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ExampleObject>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ExampleObject to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ExampleObject from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ExampleObject instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ExampleObject fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of the user account on Thecodebuzz.com */
  @Deprecated public java.lang.CharSequence field1;
  /** The email of the user logging message on the blog */
  @Deprecated public java.lang.CharSequence field2;
  /** time in seconds */
  @Deprecated public long field3;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ExampleObject() {}

  /**
   * All-args constructor.
   * @param field1 Name of the user account on Thecodebuzz.com
   * @param field2 The email of the user logging message on the blog
   * @param field3 time in seconds
   */
  public ExampleObject(java.lang.CharSequence field1, java.lang.CharSequence field2, java.lang.Long field3) {
    this.field1 = field1;
    this.field2 = field2;
    this.field3 = field3;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return field1;
    case 1: return field2;
    case 2: return field3;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: field1 = (java.lang.CharSequence)value$; break;
    case 1: field2 = (java.lang.CharSequence)value$; break;
    case 2: field3 = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'field1' field.
   * @return Name of the user account on Thecodebuzz.com
   */
  public java.lang.CharSequence getField1() {
    return field1;
  }


  /**
   * Sets the value of the 'field1' field.
   * Name of the user account on Thecodebuzz.com
   * @param value the value to set.
   */
  public void setField1(java.lang.CharSequence value) {
    this.field1 = value;
  }

  /**
   * Gets the value of the 'field2' field.
   * @return The email of the user logging message on the blog
   */
  public java.lang.CharSequence getField2() {
    return field2;
  }


  /**
   * Sets the value of the 'field2' field.
   * The email of the user logging message on the blog
   * @param value the value to set.
   */
  public void setField2(java.lang.CharSequence value) {
    this.field2 = value;
  }

  /**
   * Gets the value of the 'field3' field.
   * @return time in seconds
   */
  public long getField3() {
    return field3;
  }


  /**
   * Sets the value of the 'field3' field.
   * time in seconds
   * @param value the value to set.
   */
  public void setField3(long value) {
    this.field3 = value;
  }

  /**
   * Creates a new ExampleObject RecordBuilder.
   * @return A new ExampleObject RecordBuilder
   */
  public static com.entity.generator.sample.ExampleObject.Builder newBuilder() {
    return new com.entity.generator.sample.ExampleObject.Builder();
  }

  /**
   * Creates a new ExampleObject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ExampleObject RecordBuilder
   */
  public static com.entity.generator.sample.ExampleObject.Builder newBuilder(com.entity.generator.sample.ExampleObject.Builder other) {
    if (other == null) {
      return new com.entity.generator.sample.ExampleObject.Builder();
    } else {
      return new com.entity.generator.sample.ExampleObject.Builder(other);
    }
  }

  /**
   * Creates a new ExampleObject RecordBuilder by copying an existing ExampleObject instance.
   * @param other The existing instance to copy.
   * @return A new ExampleObject RecordBuilder
   */
  public static com.entity.generator.sample.ExampleObject.Builder newBuilder(com.entity.generator.sample.ExampleObject other) {
    if (other == null) {
      return new com.entity.generator.sample.ExampleObject.Builder();
    } else {
      return new com.entity.generator.sample.ExampleObject.Builder(other);
    }
  }

  /**
   * RecordBuilder for ExampleObject instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ExampleObject>
    implements org.apache.avro.data.RecordBuilder<ExampleObject> {

    /** Name of the user account on Thecodebuzz.com */
    private java.lang.CharSequence field1;
    /** The email of the user logging message on the blog */
    private java.lang.CharSequence field2;
    /** time in seconds */
    private long field3;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.entity.generator.sample.ExampleObject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.field1)) {
        this.field1 = data().deepCopy(fields()[0].schema(), other.field1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.field2)) {
        this.field2 = data().deepCopy(fields()[1].schema(), other.field2);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.field3)) {
        this.field3 = data().deepCopy(fields()[2].schema(), other.field3);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ExampleObject instance
     * @param other The existing instance to copy.
     */
    private Builder(com.entity.generator.sample.ExampleObject other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.field1)) {
        this.field1 = data().deepCopy(fields()[0].schema(), other.field1);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.field2)) {
        this.field2 = data().deepCopy(fields()[1].schema(), other.field2);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.field3)) {
        this.field3 = data().deepCopy(fields()[2].schema(), other.field3);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'field1' field.
      * Name of the user account on Thecodebuzz.com
      * @return The value.
      */
    public java.lang.CharSequence getField1() {
      return field1;
    }


    /**
      * Sets the value of the 'field1' field.
      * Name of the user account on Thecodebuzz.com
      * @param value The value of 'field1'.
      * @return This builder.
      */
    public com.entity.generator.sample.ExampleObject.Builder setField1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.field1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'field1' field has been set.
      * Name of the user account on Thecodebuzz.com
      * @return True if the 'field1' field has been set, false otherwise.
      */
    public boolean hasField1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'field1' field.
      * Name of the user account on Thecodebuzz.com
      * @return This builder.
      */
    public com.entity.generator.sample.ExampleObject.Builder clearField1() {
      field1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'field2' field.
      * The email of the user logging message on the blog
      * @return The value.
      */
    public java.lang.CharSequence getField2() {
      return field2;
    }


    /**
      * Sets the value of the 'field2' field.
      * The email of the user logging message on the blog
      * @param value The value of 'field2'.
      * @return This builder.
      */
    public com.entity.generator.sample.ExampleObject.Builder setField2(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.field2 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'field2' field has been set.
      * The email of the user logging message on the blog
      * @return True if the 'field2' field has been set, false otherwise.
      */
    public boolean hasField2() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'field2' field.
      * The email of the user logging message on the blog
      * @return This builder.
      */
    public com.entity.generator.sample.ExampleObject.Builder clearField2() {
      field2 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'field3' field.
      * time in seconds
      * @return The value.
      */
    public long getField3() {
      return field3;
    }


    /**
      * Sets the value of the 'field3' field.
      * time in seconds
      * @param value The value of 'field3'.
      * @return This builder.
      */
    public com.entity.generator.sample.ExampleObject.Builder setField3(long value) {
      validate(fields()[2], value);
      this.field3 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'field3' field has been set.
      * time in seconds
      * @return True if the 'field3' field has been set, false otherwise.
      */
    public boolean hasField3() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'field3' field.
      * time in seconds
      * @return This builder.
      */
    public com.entity.generator.sample.ExampleObject.Builder clearField3() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ExampleObject build() {
      try {
        ExampleObject record = new ExampleObject();
        record.field1 = fieldSetFlags()[0] ? this.field1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.field2 = fieldSetFlags()[1] ? this.field2 : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.field3 = fieldSetFlags()[2] ? this.field3 : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ExampleObject>
    WRITER$ = (org.apache.avro.io.DatumWriter<ExampleObject>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ExampleObject>
    READER$ = (org.apache.avro.io.DatumReader<ExampleObject>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.field1);

    out.writeString(this.field2);

    out.writeLong(this.field3);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.field1 = in.readString(this.field1 instanceof Utf8 ? (Utf8)this.field1 : null);

      this.field2 = in.readString(this.field2 instanceof Utf8 ? (Utf8)this.field2 : null);

      this.field3 = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.field1 = in.readString(this.field1 instanceof Utf8 ? (Utf8)this.field1 : null);
          break;

        case 1:
          this.field2 = in.readString(this.field2 instanceof Utf8 ? (Utf8)this.field2 : null);
          break;

        case 2:
          this.field3 = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










